services:
  jupyter:
    container_name: jupyter_for_ds
    image: quay.io/jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      DOCKER_STACKS_JUPYTER_CMD: ${DOCKER_STACKS_JUPYTER_CMD}

